### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by simonrb2000** [45clouds/homebridge-ip-camera#1]
Not installed yet, just wondered how much CPU this takes? Was looking at adding multiple cameras.. However saying that I suppose it only uses the CPU when viewing the stream.. Also is there a minimum version of node required? I also noticed you say install ffmpeg onto raspberry pi 3, I've not seen anywhere the best way to do this? 

Looks very promising as I have the Foscam C1 and that doesn't work with the Foscam Hombridge plugin.

**Comment by 45clouds** [comment]
My environment: Raspberry Pi 3 + Synologic NAS (I store recording from my cameras on it using Surveillance Station) and 4 IP cameras (HikVision). You are right: it uses CPU when you view the stream (a call to ffmpeg binary). The CPU usage is about 30-40% on my setup. It's OK because there are no other critical functions on this PI3. Please look at these instructions to install ffmpeg on PI3. It worked for me without any issues:

https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian

My setup contains node v 6.9.1, but it should work with 4.x. 

Let me know if you have any problems and I will try to help you. 

Best regards,

**Comment by simonrb2000** [comment]
Thanks for your reply.. you link refers to motion, I assume I only need to do steps 1 & 2, just backing up my card then I'll be having ago at it.. 

Kind Regards!

**Comment by simonrb2000** [comment]
Having issues with my config file, its the camera bit the throws me.

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "DD:33:4E:F4:DF:32",
		"port": 51927,
		"pin": "031-45-154"
	},


	"platforms": [{
		"platform": "eDomoticz",
		"name": "eDomoticz",
		"server": "127.0.0.1",
		"port": "8080",
		"roomid": "4",
		"loadscenes": "0",
		"mqttenable": 1,
		"mqttserver": "127.0.0.1",
		"mqttport": "1883",
		"mqttauth": 0,
		"mqttuser": "",
		"mqttpass": ""
	}, {

	"platform": "Camera-IP",
  "cameras": [
    {
		"name": "Garage",
		"videoConfig": {
			"source": "-re -i rtsp://username:password@192.168.1.237:554/videoMain",
			"stillImageSource": "-i http://192.168.1.237:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=&pwd=",
			"maxStreams": 2,
			"maxWidth": 1280,
			"maxHeight": 720,
			"maxFPS": 30
		}
	}]
}
```

**Comment by simonrb2000** [comment]
Sorted it! And its worked first time! Brilliant stuff! Thank you!

**Comment by 45clouds** [comment]
Great! Happy viewing 👍

**Comment by simonrb2000** [comment]
One last question, I had ffmpeg already setup from a while back so just used that. I am finding that the first 5 seconds of the video are smooth then after that it is very choppy and my CPU is around the 70% and I'm on a raspberry pi. Maybe I should remove and try the method you suggested if your video is smooth.. my camera can do mjpeg natively - would that save me having to convert? Cheers
